PROCESS BEFORE OUTPUT.
 MODULE STATUS_0101.
 MODULE DEFAULT_RADIOBUTTON.
*
PROCESS AFTER INPUT.
 MODULE USER_COMMAND_0101.

PROCESS ON VALUE-REQUEST.
   FIELD scr_0101-arquivo MODULE f4_arquivo.